/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DBMS.Project;

/**
 *
 * @author nishit
 */
public class GUIScreen extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public GUIScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        inputKey = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        insert = new javax.swing.JButton();
        search = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 886, 510));
        setMinimumSize(new java.awt.Dimension(886, 510));
        setSize(new java.awt.Dimension(886, 510));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("EXTENDIBLE HASHING");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(170, 0, 570, 90);

        inputKey.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inputKey.setBorder(new javax.swing.border.MatteBorder(null));
        inputKey.setDebugGraphicsOptions(javax.swing.DebugGraphics.FLASH_OPTION);
        inputKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputKeyActionPerformed(evt);
            }
        });
        getContentPane().add(inputKey);
        inputKey.setBounds(440, 120, 140, 30);

        jLabel3.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Enter Key :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(310, 120, 130, 28);

        insert.setIcon(new javax.swing.ImageIcon("C:\\module-2\\Images\\button_insert.png"));
        getContentPane().add(insert);
        insert.setBounds(80, 180, 150, 50);

        search.setIcon(new javax.swing.ImageIcon("C:\\module-2\\Images\\button_search.png"));
        getContentPane().add(search);
        search.setBounds(670, 180, 150, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\module-2\\Images\\nackg.png")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 890, 510);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputKeyActionPerformed
        
    }//GEN-LAST:event_inputKeyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        System.out.println("GUI Java");
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField inputKey;
    private javax.swing.JButton insert;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton search;
    // End of variables declaration//GEN-END:variables
}
